### ISSUE TITLE
Experimental values and predictions

### ISSUE THREAD

**Issue by JenniferHem** [kmansouri/OPERA#19]
Hi @kmansouri ,

I have been using OPERA and currently it works well in the GUI and also via python. Now I would like to do a comparison of OPERA to our internal tools for KOC prediction. However, when I used the validation data from OPERA (downloaded from the QMRF report) and predicted this dataset with the OPERA KOC model I got an RMSE of 0.1 with an R² of 0.99. 

It looks like I do not get predictions, rather I get the experimental values stored in the training dataset. I could not find anything documented for this behavior so I just would like to make sure that my assumption is correct and I always get an experimental value if a molecule is present in the training (or test?) dataset. Is this correct? If so, is there a way to check which returned values are actual predictions and which were part of the training/test data? This would be essential if we want to compare OPERA to our internal tools. 

Thanks in advance for your clarification.

**Comment by kmansouri** [comment]
OPERA does not provide the experimental value unless it is requested (in the output option) and that requires the presence of a CAS or DTXSID in the input file to get the exact experimental value. However, since the KOC model is a kNN model (weighted by distance as explained in the QMRF), when you predict a structure that is in the knowledge base of OPERA it'll have most of the weight on the nearest neighbor which is the same chemical in tat case and very little from the other neighbors. To get the training vs test stats of OPERA models please refer to the QMRF reports as well as the publications cited on the repo page.

Best!
Kamel
