### ISSUE TITLE
Place an error flag in the csv when failing for one molecule instead of giving up everything?

### ISSUE THREAD

**Issue by leoliu0** [kmansouri/OPERA#25]
Thank you for the great tool!

I am using the parallel version. Just wondering if we can replace the current failing behaviour for one or more molecules. Instead of giving up and output nothing. Can we just output the rest of the results and place an error indicator in the output file?

**Comment by kmansouri** [comment]
The parallel version is different because it distributes different chunks to each processor. If one of them fails, reconstructing the chunks can result in errors. 
The regular version would give you an output even if one or multiple chemicals fail. 
I wouldn't recommend the parallel version unless your running more than 5-10k chemicals anyway.
