### ISSUE TITLE
Opera 2.8 - issues with the structural-standardization

### ISSUE THREAD

**Issue by lidiaceriani0305** [kmansouri/OPERA#28]
Hello,
I just installed the new OPERA 2.8 version, and I'm encountering the same error, no matter which input file I use (mol, sdf, smi, txt) : No structures passed standardization. Check input file!
This issues also occurs with the mol files provided by the US EPA CompTox Chemicals Dashboard. 
I currently have installed the KNIME  version 4.5.2 on my PC. Could it be that this version of KNIME is creating some issues with the implemented QSAR-ready workflow? Other users have experienced similar issues with this new version of opera?
Thank you for your feedback!
Best,
Lidia

**Comment by tsufz** [comment]
Hi @kmansouri,
I encounter the problem in 2.9 cl opera_p as well. I gues some link is missing to KNIME. It does work without the `-st` switch:
![image](https://user-images.githubusercontent.com/2526819/200174824-c45e604d-fe92-49a1-8c19-22c03c7c50e0.png)

**Comment by kmansouri** [comment]
@tsufz because of a limit in the size of the package on Github and the fact that OPERA parallel version was already a big package, the standardizer had a packaging issue for the (opera_p only). I am working on a solution. In the meanwhile you can install the regular OPERA Cl version (in the same parent folder as opera_p) and they will both share the same standardizer.

**Comment by tsufz** [comment]
@kmansouri, I use the latest version, but the issue is still remaining....
